// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_cognito_identity_pool_id:
    "ap-northeast-1:95172fe3-c15f-4e1c-a78a-6a9eee872e12",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_vuCcLZLAN",
  aws_user_pools_web_client_id: "7p7dis2ifq8g52eqj3ok3ar7gb"
};

export default awsmobile;
