// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b28edda1-69aa-4a00-ac65-b191719ade7f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_jVEwHJy0B",
    "aws_user_pools_web_client_id": "7mjdu064m99ksv60a6d5e1u5go"
};


export default awsmobile;
